Revert "Import org.junit.Assert instead of junit.framework.Assert."
This reverts commit a88470964c55dc655022d1f46370565aa3be535f.

It broke Android builds:
app/webrtc/java/testcommon/src/org/webrtc/PeerConnectionTest.java:46: error: package org.junit does not exist
import static org.junit.Assert.*;
                       ^
TBR=glaznev@webrtc.org,pthatcher@webrtc.org
BUG=none

Review URL: https://webrtc-codereview.appspot.com/52039004

Cr-Original-Commit-Position: refs/heads/master@{#9357}
Cr-Mirrored-From: https://chromium.googlesource.com/external/webrtc
Cr-Mirrored-Commit: 6b990744d9c3b4aa4ce5c4db585acff7285c75cc