Disable flaky RapidSpeakerChange test.
Example:
chromegw/i/internal.client.webrtc/builders/Win32%20Debug/builds/762/steps/libjingle_p2p_unittest/logs/stdio

e:\b\build\slave\win32_debug\build\src\talk\session\media\currentspeakermonitor_unittest.cc(144):
error: Value of: kSsrc2
  Actual: 1002
Expected: current_speaker_
Which is: 1001
e:\b\build\slave\win32_debug\build\src\talk\session\media\currentspeakermonitor_unittest.cc(145):
error: Value of: 1
Expected: num_changes_
Which is: 2
[  FAILED  ] CurrentSpeakerMonitorTest.RapidSpeakerChange (16 ms)

TBR=wu@webrtc.org
BUG=2409

Review URL: https://webrtc-codereview.appspot.com/2318004

Cr-Mirrored-From: https://chromium.googlesource.com/external/webrtc
Cr-Mirrored-Commit: 4475905613cc5d05815b83d8f3cb3ff029fd3191